# Generated by Django 5.0.2 on 2024-02-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField(default='0')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=100)),
                ('unit', models.IntegerField(default='0', max_length=10)),
                ('amount', models.IntegerField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField(default='0')),
                ('previous', models.IntegerField(max_length=10)),
                ('reading', models.IntegerField(max_length=10)),
                ('tmonth', models.IntegerField()),
                ('tyear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tanker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(default='0')),
                ('ttanker', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('stenant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField(default='0')),
                ('tname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=10)),
                ('contact', models.IntegerField(default='0', max_length=10)),
                ('rent', models.IntegerField(default='100')),
                ('date', models.DateField()),
            ],
        ),
    ]
