# Generated by Django 5.0.2 on 2024-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='profile')),
            ],
        ),
    ]
