# Generated by Django 5.0.2 on 2024-04-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenantproject', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='rent',
        ),
    ]
