# Generated by Django 5.0.2 on 2024-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantproject', '0004_tenant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='username',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='sub',
            name='username',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
