# Generated by Django 5.0.2 on 2024-04-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenantproject', '0006_tanker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanker',
            name='username',
        ),
    ]
