# Generated by Django 5.0.2 on 2024-04-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenantproject', '0007_remove_tanker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='username',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='username',
        ),
    ]
